version: '3.8'

services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: modern-ai-chatbot
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=3000
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - chatbot-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  chatbot-network:
    driver: bridge

volumes:
  logs:
    driver: local
